# Generated by Django 5.1.1 on 2024-09-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal_dev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating_user',
            new_name='_rating_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='_rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='_rating',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'Статья'), ('news', 'Новость')], max_length=7),
        ),
    ]
